import { CONTEXT_RECENT_TURNS_LIMITS } from '../../../shared/config/constants.js';

export const DOM_IDS = {
    MODAL: 'settings-modal',
    BTN_CLOSE: 'close-settings',
    BTN_SAVE_SHORTCUTS: 'save-shortcuts',
    SAVE_STATUS: 'settings-save-status',
    BTN_RESET_SHORTCUTS: 'reset-shortcuts',
    TAB_TITLE: 'settings-tab-title',

    TEXT_SELECTION_TOGGLE: 'text-selection-toggle',
    TEXT_SELECTION_BLACKLIST: 'text-selection-blacklist',
    IMAGE_TOOLS_TOGGLE: 'image-tools-toggle',
    IMAGE_TOOLS_BLACKLIST: 'image-tools-blacklist',
    GENERATED_IMAGE_WATERMARK_TOGGLE: 'generated-image-watermark-toggle',
    ACCOUNT_INDICES: 'account-indices-input',
    CONTEXT_MODE: 'context-mode-select',
    INPUT_RECENT_TURNS: 'context-recent-turns-input',
    CONTAINER_SELECTION_TOOLS: 'custom-selection-tools-list',
    BTN_ADD_SELECTION_TOOL: 'add-custom-selection-tool',

    PROVIDER_SELECT: 'provider-select',
    API_KEY_CONTAINER: 'api-key-container',
    WEB_FIELDS: 'web-fields',
    WEB_TEMPORARY_CHAT: 'web-temporary-chat-enabled',
    OFFICIAL_FIELDS: 'official-fields',
    OFFICIAL_BASE_URL: 'official-base-url',
    OFFICIAL_API_KEY: 'api-key-input',
    OFFICIAL_MODEL: 'official-model',
    OFFICIAL_THINKING_LEVEL: 'thinking-level-select',
    OFFICIAL_WEB_SEARCH: 'official-web-search-enabled',

    OPENAI_FIELDS: 'openai-fields',
    OPENAI_BASE_URL: 'openai-base-url',
    OPENAI_API_KEY: 'openai-api-key',
    OPENAI_MODEL: 'openai-model',
    OPENAI_THINKING_LEVEL: 'openai-thinking-level-select',
    OPENAI_USE_RESPONSES_API: 'openai-use-responses-api',
    OPENAI_WEB_SEARCH: 'openai-web-search-enabled',
    SUMMARY_MODEL: 'summary-model-input',

    DEDICATED_API_FIELDS: 'dedicated-api-fields',
    DEDICATED_API_BASE_URL: 'dedicated-api-base-url',
    DEDICATED_API_API_KEY: 'dedicated-api-api-key',
    DEDICATED_API_MODEL: 'dedicated-api-model',
    DEDICATED_API_REFRESH_MODELS: 'dedicated-api-refresh-models',
    DEDICATED_API_MODEL_LIST_STATUS: 'dedicated-api-model-list-status',
    DEDICATED_API_THINKING_LEVEL: 'dedicated-api-thinking-level-select',
    DEDICATED_API_WEB_SEARCH_ROW: 'dedicated-api-web-search-row',
    DEDICATED_API_WEB_SEARCH: 'dedicated-api-web-search-enabled',
    DEDICATED_API_PROVIDER_ROUTING_ROW: 'dedicated-api-provider-routing-row',
    DEDICATED_API_PROVIDER_ROUTING: 'dedicated-api-provider-routing',

    MCP_ENABLED: 'mcp-enabled',
    MCP_FIELDS: 'mcp-fields',
    MCP_SERVER_SELECT: 'mcp-server-select',
    MCP_ADD_SERVER: 'mcp-add-server',
    MCP_REMOVE_SERVER: 'mcp-remove-server',
    MCP_SERVER_NAME: 'mcp-server-name',
    MCP_TRANSPORT: 'mcp-transport',
    MCP_SERVER_URL: 'mcp-server-url',
    MCP_HEADERS: 'mcp-headers',
    MCP_SERVER_ENABLED: 'mcp-server-enabled',
    MCP_TEST_CONNECTION: 'mcp-test-connection',
    MCP_TEST_STATUS: 'mcp-test-status',
    MCP_TOOL_MODE: 'mcp-tool-mode',
    MCP_REFRESH_TOOLS: 'mcp-refresh-tools',
    MCP_ENABLE_ALL_TOOLS: 'mcp-enable-all-tools',
    MCP_DISABLE_ALL_TOOLS: 'mcp-disable-all-tools',
    MCP_TOOL_SEARCH: 'mcp-tool-search',
    MCP_TOOLS_SUMMARY: 'mcp-tools-summary',
    MCP_TOOL_LIST: 'mcp-tool-list',

    THEME_SELECT: 'theme-select',
    LANGUAGE_SELECT: 'language-select',
    OPACITY_SLIDER: 'opacity-slider',
    OPACITY_VALUE: 'opacity-value',
    TOOLBAR_TEXT_TOGGLE: 'toolbar-text-toggle',
    BUBBLE_TOGGLE: 'bubble-toggle',
    BUBBLE_CLICK_ACTION: 'bubble-click-action',
    EXPLAIN_PAGE_CONTEXT_TOGGLE: 'explain-page-context-toggle',
    SHORTCUT_QUICK_ASK: 'shortcut-quick-ask',
    SHORTCUT_PAGE_CHAT: 'shortcut-page-chat',
    SHORTCUT_OPEN_PANEL: 'shortcut-open-panel',
    SHORTCUT_SUMMARIZE_PAGE: 'shortcut-summarize-page',
    SHORTCUT_BROWSER_CONTROL: 'shortcut-browser-control',
    SHORTCUT_OCR_CAPTURE: 'shortcut-ocr-capture',
    DOWNLOAD_LOGS: 'download-logs',
    EXPORT_HISTORY_DATA: 'export-history-data',
    IMPORT_HISTORY_DATA: 'import-history-data',
    IMPORT_HISTORY_FILE: 'import-history-file',
    EXPORT_SETTINGS_DATA: 'export-settings-data',
    IMPORT_SETTINGS_DATA: 'import-settings-data',
    IMPORT_SETTINGS_FILE: 'import-settings-file',
    ABOUT_GROUP: 'about-settings-group',
    APP_CURRENT_VERSION: 'app-current-version',
    APP_UPDATE_STATUS: 'app-update-status',
    STAR_COUNT: 'star-count',
};

export const CONFIG_LIMITS = {
    RECENT_TURNS: CONTEXT_RECENT_TURNS_LIMITS,
};
